version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Expose le port de l'application
    environment:
      - NODE_ENV=production
    volumes:
      - .:/frontend/app
